### PR TITLE
feature(assertj-db): add support to UUID column type

### PR DESCRIPTION
**Pull request by otoniel-isidoro-sofist**

### CODE REVIEW

**Comment by otoniel-isidoro-sofist** [comment]
See https://github.com/joel-costigliola/assertj-db/issues/15

**Comment by otoniel-isidoro-sofist** [comment]
For while I added the UUID type but I will try later implement a generic type to turn it possible to make assertions on any column type that is not mapped on assertj-db.

**Comment by regis1512** [comment]
Hi,

Thanks for your job.
Just there are some mistakes :
- "assertj-eclipse-formatter.xml" was updated since 17th of February and now the tab indentation is 2 (line 169 : https://github.com/joel-costigliola/assertj-core/blob/master/src/ide-support/assertj-eclipse-formatter.xml). So please make no changes on the formatting of the files especially because that makes the comparison less easy.
- Take care about having one and only one blank line before and after method (for examples : AbstractAssertWithValues.isUUID(), AssertOnColumnEquality.hasValues(UUID...) and may be other but i did not verify). I am a little bit obsessed about that but i think it is more beautiful. ;-)
- in AssertOnValueType file, at line 37, 68, 99, 177 and 333, you make modifications but the javadoc was correct before your modifications and not correct after. In fact, value() methods possibilities are different from a colum and from a row : from a row it exists a value(String) method with the name of a column
- it is difficult to see because of the difference of formatting but i think it is good to add a areEqual(UUID, String) method to make possible the comparison between a UUID in database with a String

Otherwise, i think that is a very good job.
Especially because i know it is not easy to enter so quickly in the code of somebody else.

For information, i use IntelliJ because for me Eclipse is not able to well compile the project (i think too much generics)
Just to know if you met the same problems : which is you IDE ?

**Comment by otoniel-isidoro-sofist** [comment]
Thanks for the reply @regis1512 , is good to know that you are keeping attention on this project. I agree with all your points and I will make the fixes until friday.
I think this project is very good and useful in special cases, for example when is necessary to test persistence layers that doesn't have methods to retrieve data to make assertions on java objects. Then, instead of the "tester" has to do an hard task as implement database helpers and complex rowMappers to retrieve the data, they can simply use assertj-db and make the assertions directly on the table data.
Certainly it is useful to increase the maintainability of the tests too.
Thanks for your review and support!

**Comment by otoniel-isidoro-sofist** [comment]
I almost forgot to reply your question. I use IntelliJ too. thx.

**Comment by regis1512** [comment]
:) Thx for you interest.

**Comment by otoniel-isidoro-sofist** [comment]
Just to warn you: Some classes like AssertionsOnColumnOfChangeType.java and Values.java are using 4 spaces indentation yet.

**Comment by otoniel-isidoro-sofist** [comment]
I've applied the fixes and I added the areEqual(UUID,String) too as you suggested. The tests were also updated.

**Comment by regis1512** [comment]
Very good job.
Just two last things :
- please add your name in the @author of each classes you have worked (i mean the classes with real changes not the classes with wrong formatting ;-)) : there is my name so if there is some credits to you it is logic to indicate
- i think the next release will be 1.1.0 so please add tag @since 1.1.0 to javadoc of the methods you add (i think it is in the classes AssertOnColumnEquality, AssertOnColumnOfChangeEquality, AssertOnColumnOfChangeEquality, AssertOnValueEquality, AssertOnValueNonEquality, AssertOnValueNonEquality and Values) and may be for UUID constant in ValueType (i do not know the effect for a instance variable).

For information, i plan to change the version to 2.0.0 with migration to Java 8 (but i wait that Java 8 become regular in the enterprises and from my experience it is sometimes slower than for personal uses).

I will not available on saturday and sunday so if you need time do not care

Thanks.

**Comment by otoniel-isidoro-sofist** [comment]
Done.

**Comment by regis1512** [comment]
Fine

**Pull request merged**
