### PR TITLE
Add isEmpty assertion

### PR DESCRIPTION
**Pull request by fiery-phoenix**
Added isEmpty assertion requested at #12

### CODE REVIEW

**Comment by joel-costigliola** [comment]
@fiery-phoenix this is not related to that issue but if I'm correct you own @assertj twitter account, right ?

**Comment by fiery-phoenix** [comment]
@joel-costigliola yes, I can change it, but will need time to come up with other name

**Comment by joel-costigliola** [comment]
@fiery-phoenix that would awesome, I was thinking to create @assertj twitter account but was procrastinating thinking that nobody would have registered it, I was wrong :smile:

**Comment by fiery-phoenix** [comment]
done

**Comment by joel-costigliola** [comment]
@fiery-phoenix many thanks !

**Comment by fiery-phoenix** [comment]
you are welcome :)

**Comment by regis1512** [comment]
Thanks.
Good job.

**Pull request merged**
