### PR TITLE
Add Clob support

### PR DESCRIPTION
**Pull request by otoniel-isidoro-sofist**

### CODE REVIEW

**Comment by regis1512** [comment]
OK. I will see that tomorrow.

**Comment by regis1512** [comment]
For information, i have just added a new page in the documentation to list the releases with the contributing on these releases : http://joel-costigliola.github.io/assertj/assertj-db-news.html

**Comment by regis1512** [comment]
I start to see the pull request but i am not sure to finish tonight.

**Comment by otoniel-isidoro-sofist** [comment]
Hello @regis1512 thanks for the mention on the page but my name is wrong there. The correct is Otoniel Isidoro. Thx.

**Comment by otoniel-isidoro-sofist** [comment]
I forgot some tests to other mapped SQL types on AbstractDbData class. When I have some time I'll do this.

**Comment by regis1512** [comment]
I fix the name (sorry usually i copy/paste and it is better ;-)).
For the tests, wait because i saw you added many types.
But i prefer one type per pull request : it will be easier to validate.
After i am not yet sure but i think you fork before last pull request validation because the comparison is strange. I will see that this evening (in France it is 08:15am and i need to go to work).

**Pull request closed without merging**
